//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICECEKLER
    {
        public int ICECEKLERID { get; set; }
        public string ICECEKADI { get; set; }
        public string FOTOGRAF { get; set; }
        public Nullable<decimal> ICECEKFIYAT { get; set; }
    }
}
