//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAHVALTI
    {
        public int KAHVALTID { get; set; }
        public string KAHVALTIADI { get; set; }
        public string KAHVALTICERIK { get; set; }
        public Nullable<decimal> KAHVALTIFIYAT { get; set; }
        public string FOROGRAF { get; set; }
    }
}
