//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public int PERSONELID { get; set; }
        public string PERSONELADI { get; set; }
        public string PERSONELSOYADI { get; set; }
        public string KULLANICIADI { get; set; }
        public string SIFRE { get; set; }
    }
}
