//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISLER
    {
        public int SIPARISID { get; set; }
        public int PERSONELID { get; set; }
        public System.DateTime SIPARISTARIHI { get; set; }
        public Nullable<decimal> SIPARISTUTARI { get; set; }
        public string ODEMETIPI { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
