//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TATLILAR
    {
        public int TATLID { get; set; }
        public string TATLIADI { get; set; }
        public string TATLICERIK { get; set; }
        public string FOROGRAF { get; set; }
        public Nullable<decimal> TATLIFIYAT { get; set; }
    }
}
